#########################################################
# Gradle                                                #
#########################################################
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

#########################################################
# Minecraft Version (Forge 1.20.1)                      #
#########################################################
parchment_version=2023.08.20-1.20.1
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
loader_version_range=[46,)

#########################################################
# Mod Info                                              #
#########################################################
mod_id=tlm_mimo_tts
mod_name=TLM MiMo TTS
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.xm2nd
mod_authors=xm2nd
mod_description=TLM MiMo TTS: \u4e3a Touhou Little Maid \u5973\u4ec6 AI \u804a\u5929\u63a5\u5165\u5c0f\u7c73 MiMo \u8bed\u97f3\u5408\u6210\uff08\u9884\u7f6e\u97f3\u8272\u4e0e\u8bed\u97f3\u514b\u9686\uff09\u7684\u9644\u5c5e Mod\u3002
